api/urls.py
from django.urls import path
from api import views


urlpatterns = [
    path("api-view/", views.NameList.as_view()),
    path('<int:pk>/', views.NameDetail.as_view()),
    # path('routes/', views.getRoutes),
    # path('routes/api/quesionnaire/', views.getQuestionnaires),
    # path('routes/api/quesionnaire/create', views.CreateQuestionnaire),
    # path('routes/api/quesionnaire/<str:pk>/update/', views.updateQuestionnaire),
    # path('routes/api/quesionnaire/<str:pk>/delete/', views.deleteQuestionnaire),
    # path('routes/api/quesionnaire/<str:pk>/', views.getQuestionnaire)
   

]

dashboard/urls.py
from django.urls import path
from . import views

# app_name = "dashboard"

urlpatterns = [
    path("", views.index, name="dashboard"),
    path("charts/", views.charts, name="charts"),
    path("users/", views.users, name="users"),
    path("questionnaire/", views.questionnaires, name="questionnaire"),
    path("new-questionnaire/", views.new_questionnaire, name="new_questionnaire"),
    path('dbfetch/', views.dbfetch, name='dbfetch'),
    path('register/', views.RegisterPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reports/', views.Reports, name='reports'),
    path('create-reports/', views.new_report, name='create-reports'),

    
    path("api/", views.DesignationsList.as_view()),
    path('<int:pk>/', views.DesignationsDetail.as_view()),
    path("api/survey", views.SurveyList.as_view()),
    path('<int:pk>/', views.SurveyDetail.as_view()),



]

psurvey/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('api/', include('api.urls')),
]

api/models.py
from django.db import models

# Create your models here.
class Name(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField()

    def __str__(self):
        return self.title

class Questionnaire(models.Model):
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[0:50]

    class Meta:
        ordering = ['-updated']        

dashboard/models.py
from django.db import models
# from Auth.models import Facility, Users
from datetime import datetime


# Create your models here.

#designations model
class Designations(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField()
    date_added =models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title  

# survey model
class Survey(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField()
    date_added = models.DateField(auto_now_add=True)  

class TestQuestionnaire(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=750)
    isActive = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    number_of_questions = models.BigIntegerField(default=4)
    active_till = models.DateField(datetime.now)
    target_app = models.CharField(max_length=45)

    class Meta:
    
        db_table = "TestQuestionnaires"    


class QuestionnaireApi(models.Model):
    
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=750)
    isActive = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    number_of_questions = models.BigIntegerField(default=4)
    active_till = models.DateField(datetime.now)
    target_app = models.CharField(max_length=45)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name[0:50]

    class Meta:
        db_table = "QuestionnaireApis"
        ordering = ['-updated']


class Report(models.Model):
    
    title = models.CharField(max_length=100)
    isActive = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    number_of_male = models.BigIntegerField(default=4)
    number_of_female = models.BigIntegerField(default=4)
    number_of_reports = models.BigIntegerField(default=4)
    target_app = models.CharField(max_length=45)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title[0:50]

    class Meta:
        db_table = "Final"
        ordering = ['-updated']
                                    
                            

dashboard/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CreateUserForm(UserCreationForm):
    # email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            
            'email',
            'password1',
            'password2'
        )


class LoginForm(forms.Form):
    msisdn = forms.CharField(
        max_length=15,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control ',
                'placeholder': 'Phone number'
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

class DataForm(forms.ModelForm):

    class Meta : 
          fields = ['name','description','active_till','isActive','number_of_questions', 'target_app']   
          model = QuestionnaireApi  

  

dashboard/views.py
from django.shortcuts import render , redirect
from rest_framework import generics
from .models import Designations , Survey, TestQuestionnaire , QuestionnaireApi , Report 
from django.db.models import Sum , Avg 
from .serializers import DesignationsSerializer,SurveySerializer,QuestionnaireApiSerializer , ReportSerializer
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .forms import DataForm , CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate , login , logout
from django.contrib.auth.models import User
from rest_framework.decorators import api_view
from rest_framework.response import Response
import pandas as pd
# auth
from django.contrib.auth.forms import UserCreationForm

# from Auth.serializer import *

# Create your views here.
class DesignationsList(generics.ListCreateAPIView):
    queryset = Designations.objects.all()
    serializer_class = DesignationsSerializer

class DesignationsDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Designations.objects.all()
    serializer_class = DesignationsSerializer   
#for survey
class SurveyList(generics.ListCreateAPIView):
    queryset = Survey.objects.all()
    serializer_class = SurveySerializer

class SurveyDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Survey.objects.all()
    serializer_class = SurveySerializer   

 # for questionnaire
class QuestionnaireApiList(generics.ListCreateAPIView):
    queryset = QuestionnaireApi.objects.all()
    serializer_class = QuestionnaireApiSerializer

class QuestionnaireApiDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = QuestionnaireApi.objects.all()
    serializer_class = QuestionnaireApiSerializer   
 
# for reports
class ReportList(generics.ListCreateAPIView):
    queryset = Report.objects.all() 
    serializer_class = ReportSerializer

class ReportDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Report.objects.all()
    serializer_class = ReportSerializer

@login_required(login_url='login')
def index(request):
    qs = Report.objects.all()
    total = Report.objects.all().count()
    active = Report.objects.filter(isActive=True).count()
    num_of_reports= Report.objects.aggregate(Total=Sum('number_of_reports'))['Total']
    # creating querset for dynamic chart update with model
    qs = Report.objects.all().values()
    df= pd.DataFrame(qs)
    df1 = df.title.tolist()
    df = df['number_of_reports'].tolist()
    # create queryset for gender participation update
    query_set= Report.objects.all().values()
    m_num= pd.DataFrame(query_set)
    q_title=m_num.title.tolist()
    m_num=m_num['number_of_male'].tolist()
    query_set2 = Report.objects.all().values()
    f_num=pd.DataFrame(query_set2)
    f_num=f_num['number_of_female'].tolist()
    q_performance = Report.objects.aggregate(Total=Avg('number_of_reports'))['Total']/num_of_reports * 100
    value = q_performance
    rounded = (round(value, 1))
    
    
   
   
    


    
    

    context = {'total':total , 'active':active, 'num_of_reports':num_of_reports ,
               'q_performance':q_performance ,"rounded":rounded ,  'df':df, 
        'df1':df1 , 'q_title':q_title ,'m_num':m_num, 'f_num':f_num }
    return render(request, 'dashboard/index.html',
     context 
  
    )


def charts(request):
    return render(request, 'dashboard/charts.html')

@login_required(login_url='login')
def new_questionnaire(request):
    
    if request.method == 'POST' :
        post = QuestionnaireApi()
        post.name = request.POST.get('title')
        post.status = request.POST.get('isActive')
        post.description = request.POST.get('description')
        post.active_till = request.POST.get('active_till')
        post.num_questions = request.POST.get('number_of_questions')
        post.target_app =  request.POST.get('target_app')
        
        post.save()
        return HttpResponse('Database updated successfuly with New Questionnaire')
           
    return  render(request, "dashboard/new_questionnaire.html")
       
    
def users(request):

    return render(request, "dashboard/users.html")

def RegisterPage(request):

    if request.user.is_authenticated :
        return redirect('dashboard')
    else:
        
        form = CreateUserForm()
        context = {'form': form}    
        if request.method == 'POST':
           form = CreateUserForm(request.POST)
           if form.is_valid():
               form.save()
           user = form.cleaned_data.get('username')
           messages.success(request, 'account was created successfully for ' + user )
           return redirect('login')
        #    messages.info(request, ' username or password does not exist ') 

    return render(request, 'accounts/reg_form.html', context)
def loginPage(request):
    if request.user.is_authenticated :
        return redirect('dashboard')
    else:    
        if request.method == 'POST':
           username = request.POST.get('username')
           password = request.POST.get('password')

           user = authenticate(request, username=username , password=password)
           if user is not None:
                login(request, user)
           return redirect('dashboard')
        else:
                # messages.info(request, ' username or password does not exist ')   
                context = {}      
    return render(request, 'accounts/login.html')

def logoutuser(request):
    logout(request)
    return redirect('login')

def dbfetch(request):
    return render(request, "dashboard/dbfetch.html")

@login_required(login_url='login')
def questionnaires(request):
    post = QuestionnaireApi.objects.all()
    count = QuestionnaireApi.objects.all().count()
    context = {'post': post, 'count':count}
    # if request.method == 'POST' :
        
        # name = request.POST.get['title']                      
        # isActive = request.GET['isActive']
        # active_till = request.GET['active_till'] 
        # number_of_questions = request.GET['num_questions']                      

        
    return render(request, "dashboard/questionnaires.html", context)
# reports

@login_required(login_url='login')
def new_report(request):
    
    if request.method == 'POST' :
        post_report = Report()
        post_report.title = request.POST.get('title')
        post_report.isActive = request.POST.get('isActive')
        # post.active_till = request.POST.get('active_till')
        post_report.number_of_male = request.POST.get('number_of_male')
        post_report.number_of_female =request.POST.get('number_of_female')
        post_report.number_of_reports = request.POST.get('number_of_reports')
        post_report.target_app = request.POST.get('target_app')
        
        post_report.save()
        return HttpResponse('Database updated successfuly with New Questionnaire Reports')
           
    return  render(request, "dashboard/new_report.html")

def Reports(request):
    post_report= Report.objects.all()
    count = Report.objects.all().count()
    context = {'post_report': post_report, 'count':count}
    # if request.method == 'POST':
        # name= request.POST.get['title']
        # isActive = request.GET['isActive']
        # number_of_reports= request.GET['number_of_reports']
        # number_of_male= request.GET['number_of_male']
        # number_of_femae=request.GET['number_of_female']

    return render(request, 'dashboard/reports.html', context)
# rest_framework views


# get all questionnaires
@api_view(['GET'])
def getQuestionnaires(request):
        Questionnaires = QuestionnaireApi.objects.all()
        serializer = QuestionnaireApiSerializer(Questionnaires, many=True)
        return Response(serializer.data)

# get Questionnaire by id
@api_view(['GET'])
def getQuestionnaire(request, pk):
        Questionnaire = QuestionnaireApi.objects.get(id=pk)
        serializer = QuestionnaireApiSerializer(Questionnaire, many=False)
        return Response(serializer.data)

# create Questionnaire
@api_view(['POST'])
def CreateQuestionnaire(request):
     
    serializer = QuestionnaireApiSerializer(data = request.data)
    if serializer.is_valid():
        serializer.save()
    return Response(serializer.data)

# update Questionnaire
@api_view(['PUT'])
def updateQuestionnaire(request, pk):
    # pk = int(pk)
    Questionnaire = QuestionnaireApi.objects.get(id=pk)
    serializer = QuestionnaireApiSerializer(instance=Questionnaire, data = request.data)
    if serializer.is_valid():
        serializer.save()
    return Response(serializer.data)    

# delete Questionnaire
@api_view(['DELETE'])
def deleteQuestionnaire(request, pk):
    pk = int(pk)
    questionnaire = QuestionnaireApi.objects.get(id=pk)
    questionnaire.delete()
    return Response('Questionnaire was deleted')     
        


    



    
    

templates/dashboard/charts.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block extra_css %}
    <style xmlns="http://www.w3.org/1999/html">
    </style>
{% endblock %}
{% block page_title %}
 Chart
{% endblock %}
{% block content %}
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Charts</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- Chart -->
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Real Time Chart</h5>
                        <div id="real-time" style="height:400px;"></div>
                        <p>Time between updates:
                            <input id="updateInterval" type="text" value="" style="text-align: right; width:5em">
                            milliseconds
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <!-- ENd chart-1 -->
     
       

{% endblock %}

templates/dashboard/dbfetch.html
<h1>{{User.last_name}}</h1>

templates/dashboard/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
       
             <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Questionnaire Dashboard</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <!-- Column -->
                    <div class="col-md-6 col-lg-3 col-xlg-3">
                        <div class="card card-hover">
                            <div class="box bg-cyan text-center">
                                <h1 class="font-light text-white"><i class="mdi mdi-briefcase-check"></i></h1>
                                <h6 class="text-white">Total Reports Submitted</h6>
                                <h6 class="text-white">{{num_of_reports}}</h6>
                            </div>
                        </div>
                    </div>
                     <!-- Column -->
                     <div class="col-md-6 col-lg-3 col-xlg-3">
                        <div class="card card-hover">
                            <div class="box bg-orange text-center">
                                <h1 class="font-light text-white"><i class="mdi mdi-calendar-check"></i></h1>
                                <h6 class="text-white">Published Questionnaires</h6>
                                <h6 class="text-white">{{total}}</h6>
                            </div>
                        </div>
                    </div>
                      <!-- Column -->
                    <!-- Column -->
                    <div class="col-md-6 col-lg-3 col-xlg-3">
                        <div class="card card-hover">
                            <div class="box bg-success text-center">
                                <h1 class="font-light text-white"><i class="mdi mdi-calendar-multiple-check"></i></h1>
                                <h6 class="text-white">Active Questionnaires</h6>
                                <h6 class="text-white">{{active}}</h6>
                            </div>
                        </div>
                    </div>
                      <!-- Column -->
                    <div class="col-md-6 col-lg-3 col-xlg-3">
                        <div class="card card-hover">
                            <div class="box bg-purple text-center">
                                <h1 class="font-light text-white"><i class="mdi mdi-chart-line"></i></h1>
                                <h6 class="text-white">Questionnaire Performance (Avg)</h6>
                                <h6 class="text-white">{{rounded}}%</h6>
                            </div>
                        </div>
                    </div>
                    <div class="container-fluid mt--6">
                        <div class="row">
                            <div class="col-xl-6">
                            <div class="card bg-defaudefault">
                                <div class="card-header bg-transparent">
                                    <div class="row align-items-center">
                                        <div class="col">
                                            <!-- <h6 class="text-light text-uppercase ls-1 mb-1">Overview</h6> -->
                                            <h5 class="h3 text-blue mb-0">Questionnaire Reports</h5>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                <canvas id="myChart" width="400" height="200"></canvas>
                            </div>
                            </div>
                                </div>
                                <div class="col-xl-6">
                                    <div class="card bg-defaudefault">
                                        <div class="card-header bg-transparent">
                                            <div class="row align-items-center">
                                                <div class="col">
                                                    <!-- <h6 class="text-light text-uppercase ls-1 mb-1">Overview</h6> -->
                                                    <h5 class="h3 text-blue mb-0">Gender Participation</h5>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card-body">
                                        <canvas id="Chart" width="400" height="200"></canvas>
                                    </div>
                                    </div>
                                        </div>
                                       
                
                </div>
            
            </div>
        </div>
                    <!-- <iframe style="background: #F1F5F4;border: none;border-radius: 2px;box-shadow: 0 2px 10px 0 rgba(70, 76, 79, .2);" width="100%" height="480"
              src="https://charts.mongodb.com/charts-project-0-pzeir/embed/dashboards?id=ee9e7273-55b3-4709-ad3e-b650980b8c7f&theme=light&autoRefresh=true&maxDataAge=3600&showTitleAndDesc=false&scalingWidth=fixed&scalingHeight=fixed"></iframe>  -->

                {% comment %} <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-md-flex align-items-center">
                                    <div>
                                        <h4 class="card-title">Response Analysis</h4>
                                        <h5 class="card-subtitle">Overview of Latest Month</h5>
                                    </div>
                                </div>
                                <div class="row">
                                   
                                    <div class="col-lg-12">
                                        <div class="row">
                                            <div class="col-6">
                                                <div class="bg-dark p-10 text-white text-center">
                                                   <i class="fa fa-user m-b-5 font-16"></i>
                                                   <h5 class="m-b-0 m-t-5">240</h5>
                                                   <small class="font-light">Total Users</small>
                                                </div>
                                            </div>
                                             <div class="col-6">
                                                <div class="bg-dark p-10 text-white text-center">
                                                   <i class="fa fa-plus m-b-5 font-16"></i>
                                                   <h5 class="m-b-0 m-t-5">20</h5>
                                                   <small class="font-light">New Users</small>
                                                </div>
                                            </div>
                                             <div class="col-6 m-t-15">
                                                <div class="bg-dark p-10 text-white text-center">
                                                   <i class="fa fa-tag m-b-5 font-16"></i>
                                                   <h5 class="m-b-0 m-t-5">6</h5>
                                                   <small class="font-light">Designations</small>
                                                </div>
                                            </div>
                                          
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
             
                    </div>
                </div>
            </div> {% endcomment %}
 {% endblock content %} 
       
    

templates/dashboard/questionnaires.html
{% extends 'base.html' %}
{% block title %}
Questionnaire

{% endblock %}
{% block headscript %}
 <style>
        @import url("https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css");

        table.view-table > tbody > tr.view td, table.view-table > tbody > tr.view th {
            cursor: pointer;
        }

        table.view-table > tbody > tr.view td:first-child,
        table.view-table > tbody > tr.view th:first-child {
            position: relative;
            padding-left: 20px;
        }

        table.view-table > tbody > tr.view td:first-child:before,
        table.view-table > tbody > tr.view th:first-child:before {
            position: absolute;
            top: 50%;
            left: 5px;
            width: 9px;
            height: 16px;
            margin-top: -8px;
            font: 16px fontawesome;
            content: "\f0d7";
            transition: all .3s ease;
        }


        table.view-table > tbody > tr.view.open {
            background: gray;
            color: white;
        }

        table.view-table > tbody > tr.view.open td:first-child:before,
        table.view-table > tbody > tr.view.open th:first-child:before {
            transform: rotate(-180deg);
            color: #333333;
        }

        table.view-table > tbody > tr.fold {
            display: none;
        }

        table.view-table > tbody > tr.fold.open {
            display: table-row;
        }

        .fold-content {
            padding: .5em;
        }

        .fold-content h3 {
            margin-top: 0;
        }

    </style>
{% endblock %}
{% block body %}
<div class="container-fluid mt--6">
<div class="col">
<div class="card">
   <div class="card-header border-0">
                    <div class="row align-items-center py-4">

                        <h3 class="mb-0">Questionnaire List</h3>
                        <div class="col-lg-6 col-5 text-right">
                            {% if u.access_level.id == 5 %}
                            {% if perms.survey.add_questionnaire %}
                            
                                    <a href="{% url 'new_questionnaire' %}" class="btn btn-sm btn-neutral">New Questionnaire</a>
                             {% endif %}
                             {% elif u.access_level.id != 4 %}
                                        <a href="{% url 'new_questionnaire' %}" class="btn btn-sm btn-neutral">New
                                            Questionnaire</a>
                             {% endif %}        
                            <button class="btn btn-sm btn-neutral" data-toggle="modal" data-target="#exampleModal">
                                Filters
                            </button>
                        </div>
                        <div class="table-responsive">
                        <p class="mx-3" style="text-align: right">
                        Questionnaire count: {{count}}
                        </p>
                        <table class="table align-items-center table-flush view-table">
                           
                        <thead class="thead-view">
                          <tr>
                          
                          <th>Serial No.</th>
                          {% comment %} <th scope="col">Created At</th> {% endcomment %}
                          <th scope="col">Title</th>
                          <th scope="col">Created At</th>
                          <th scope="col">Status</th>
                          <th scope="col">Expires</th>
                          <th scope="col">Number of Questions</th>
                          </tr>
                        </thead>
                        
                        <!--table body start-->
                       {% for QuestionnaireApi in post %}
                      <tbody class="list">
                          <tr class="view">
                                <th scope="col">{{ forloop.counter}}</th>
                                <td>{{ QuestionnaireApi.name }}</td>
                                <td>{{ QuestionnaireApi.created_at }}</td>
                                <td>{{  QuestionnaireApi.isActive }}</td>
                                <td>{{  QuestionnaireApi.active_till }}</td>
                                <td>{{  QuestionnaireApi.number_of_questions}}</td>
                                </td>
                            </tr>
                      </tbody>
                      {% endfor %}
            
                        <!--table body end-->
                        </table>
                        </div>
                    </div>
                </div>
</div>
</div>
</div>
{% endblock %}